name: MGTNTRun
main: net.overgy.TNTRun.Main
version: 0.1.0-SNAPSHOT
author: [PantallazoAzul]
description: MGTNTRun is the well known TNTRun minigame using MinigamesLib.
softdepend: [MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   tn:
      description: Main command
      usage: /tn [action]
      aliases: [tntrun, tntr]